module.exports = {
  preset: 'react-native',
  collectCoverage: true,
  timers: 'fake',
  moduleDirectories: ['node_modules'],
  transformIgnorePatterns: [
    'node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|rollbar-react-native|@fortawesome|@react-native|@react-navigation)',
  ],
  moduleNameMapper: {
    '\\.(jpg|ico|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$':
      '<rootDir>/__mocks__/fileMock.js',
    '\\.(css|less)$': '<rootDir>/__mocks__/fileMock.js',
    '~assets(.*)': '<rootDir>/assets$1',
    '@alshaya01(.*)': '<rootDir>/../../factory$1',
  },
  collectCoverageFrom: [
    '**/*.{js,jsx}',
    '!**/jest',
    '!**/node_modules/**',
    '!**/android/**',
    '!**/assets/**',
    '!index.js',
    '!**/jest.config.js',
    '!**/AppleSignIN.js',
    '!**/FBPerfCrashFix.js',
    '!**/babel.config.js',
    '!**/metro.config.js',
    '!**/coverage/**',
    '!**/react-native.config.js',
    '!**/serviceWorker.js',
    '!**/action.js',
    '!**/constants.js',
    '!**/reducer.js',
    '!**/saga.js',
    '!**/scriptdel.js',
    '!**/src/protos/**',
    '!**/src/route/**',
    '!**/src/navigation/**',
    '!**/src/buttomnavigation/indexCopy.js',
    '!**/src/buttomnavigation/index.js',
    '!**/.eslintrc.js',
    '!**/.prettierrc.js',
  ],
};
